eureka:
    instance:
        prefer-ip-address: true
    client:
        prefer-with-eureka: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8085/eureka
